# Stage 1
FROM gradle:jdk21 AS builder

WORKDIR /app


COPY ./build.gradle . 
COPY ./settings.gradle . 


COPY src ./src


RUN gradle build --no-daemon

# Stage 2
FROM openjdk:21-jdk-slim

WORKDIR /app


COPY --from=builder /app/build/libs/discografia-1.jar /app/app.jar


EXPOSE 8080


ENTRYPOINT ["java", "-jar", "/app/app.jar"]
